directories:
  output: release
  buildResources: build
appId: com.amartyamisra.flightradar
productName: FlightRadar-App
files:
  - filter:
      - dist/**/*
      - main.js
      - preload.cjs
      - package.json
asar: true
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: build/icon.ico
mac:
  target: dmg
linux:
  target: AppImage
nsis:
  oneClick: false
  perMachine: true
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
electronVersion: 30.5.1
